# Generated by Django 5.2.4 on 2025-07-20 00:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(max_length=100, unique=True, verbose_name='Nome do Banco')),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN')),
                ('nome_titular', models.CharField(max_length=100, verbose_name='Nome do Titular')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Coordenada Bancária',
                'verbose_name_plural': 'Coordenadas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Nível')),
                ('deposito_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Depósito Mínimo')),
                ('ganho_diario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Diário')),
                ('ganho_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Mensal')),
                ('ganho_anual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Anual')),
                ('ciclo_dias', models.IntegerField(verbose_name='Ciclo (dias)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
                'ordering': ['deposito_minimo'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Número de Telefone')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Sobrenome')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro da Equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Depositado')),
                ('comprovativo', models.ImageField(upload_to='comprovativos_depositos/', verbose_name='Comprovativo')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('nivel_ativar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nivel', verbose_name='Nível a Ativar')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='SaldoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Acumulado')),
                ('saldo_subsidio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo de Subsídio')),
                ('total_sacado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Sacado')),
                ('ultimo_deposito_aprovado_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Último Depósito Aprovado')),
                ('ultimo_saque_solicitado', models.DateTimeField(blank=True, null=True, verbose_name='Último Saque Solicitado')),
                ('nivel_ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nivel', verbose_name='Nível Ativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Saldo do Usuário',
                'verbose_name_plural': 'Saldos dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Solicitado')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('nome_banco_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco do Cliente')),
                ('iban_cliente', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN do Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saques', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Saque',
                'verbose_name_plural': 'Saques',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_convite', models.DateTimeField(auto_now_add=True, verbose_name='Data do Convite')),
                ('subsidy_granted', models.BooleanField(default=False, verbose_name='Subsídio Concedido')),
                ('convidado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convidado_por', to=settings.AUTH_USER_MODEL, verbose_name='Convidado')),
                ('convidante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_convites', to=settings.AUTH_USER_MODEL, verbose_name='Convidante')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'unique_together': {('convidante', 'convidado')},
            },
        ),
        migrations.CreateModel(
            name='TarefaGanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ganho', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Ganho')),
                ('data_ganho', models.DateField(auto_now_add=True, verbose_name='Data do Ganho')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nivel', verbose_name='Nível no momento da tarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganhos_tarefa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ganho de Tarefa',
                'verbose_name_plural': 'Ganhos de Tarefas',
                'ordering': ['-data_ganho'],
                'unique_together': {('usuario', 'data_ganho')},
            },
        ),
    ]
