# Generated by Django 5.2.4 on 2025-07-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de WhatsApp')),
                ('telegram_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Telegram')),
                ('whatsapp_grupo_link', models.URLField(blank=True, null=True, verbose_name='Link do Grupo de WhatsApp')),
                ('telegram_grupo_link', models.URLField(blank=True, null=True, verbose_name='Link do Grupo de Telegram')),
            ],
            options={
                'verbose_name': 'Configuração da Plataforma',
                'verbose_name_plural': 'Configurações da Plataforma',
            },
        ),
    ]
