# Generated by Django 5.2.4 on 2025-07-20 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaoplataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='coordenada_bancaria_usada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coordenadabancaria', verbose_name='Coordenada Bancária Usada'),
        ),
    ]
