# Generated by Django 5.2.4 on 2025-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deposito_coordenada_bancaria_usada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saque',
            name='iban_cliente',
        ),
        migrations.RemoveField(
            model_name='saque',
            name='nome_banco_cliente',
        ),
        migrations.AddField(
            model_name='saldousuario',
            name='banco_padrao_saque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco Padrão para Saque'),
        ),
        migrations.AddField(
            model_name='saldousuario',
            name='iban_padrao_saque',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN Padrão para Saque'),
        ),
    ]
