# Generated by Django 5.2.4 on 2025-07-21 18:28

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_referral_code_user_referred_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coordenadabancaria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deposito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='saldousuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='saque',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tarefaganho',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='comprovativo',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='ciclo_dias',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='ganho_anual',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='ganho_mensal',
        ),
        migrations.RemoveField(
            model_name='saldousuario',
            name='saldo_subsidio',
        ),
        migrations.RemoveField(
            model_name='saldousuario',
            name='ultimo_deposito_aprovado_valor',
        ),
        migrations.RemoveField(
            model_name='saque',
            name='aprovado',
        ),
        migrations.AddField(
            model_name='coordenadabancaria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposito',
            name='comprovante_pix',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes_depositos/'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='nivel',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='periodo_dias',
            field=models.IntegerField(default=365, help_text='Duração do nível em dias'),
        ),
        migrations.AddField(
            model_name='saldousuario',
            name='data_ativacao_nivel',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Ativação do Nível'),
        ),
        migrations.AddField(
            model_name='saldousuario',
            name='saldo_subsidy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo de Subsídio de Convite'),
        ),
        migrations.AddField(
            model_name='saldousuario',
            name='total_depositado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saldousuario',
            name='ultimo_deposito_aprovado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Depósito Aprovado'),
        ),
        migrations.AddField(
            model_name='saque',
            name='iban_cliente',
            field=models.CharField(default='', max_length=34, verbose_name='IBAN do Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saque',
            name='nome_banco_cliente',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Banco do Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saque',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='configuracaoplataforma',
            name='telegram_grupo_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaoplataforma',
            name='telegram_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaoplataforma',
            name='whatsapp_grupo_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaoplataforma',
            name='whatsapp_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='convite',
            name='convidante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_feitos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='convite',
            name='data_convite',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coordenadabancaria',
            name='iban',
            field=models.CharField(max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='coordenadabancaria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coordenadabancaria',
            name='nome_banco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordenadabancaria',
            name='nome_titular',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='nivel_ativar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nivel', verbose_name='Nível a Ativar'),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='deposito_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='ganho_diario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='saldousuario',
            name='nivel_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nivel', verbose_name='Nível Ativo Atual'),
        ),
        migrations.AlterField(
            model_name='saldousuario',
            name='saldo_acumulado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saldousuario',
            name='total_sacado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saldousuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saque',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saque',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saque',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saque',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tarefaganho',
            name='data_ganho',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarefaganho',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nivel'),
        ),
        migrations.AlterField(
            model_name='tarefaganho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_ganhas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefaganho',
            name='valor_ganho',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser inserido no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código de Convite'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaoplataforma',
            unique_together={('whatsapp_numero', 'telegram_numero')},
        ),
    ]
